name: Business Consulting 101
favicon: null
layout_spectrum: 0.9369646201375872
typography_spectrum: 0.15763875260017812
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7904792514164001
  lightness: 0.23481572233140469
  saturation: 0.7618516881484538
  rhythmicContrast: 0.1827712298836559
purpose: []
