name: Business Consulting DDP Group
favicon: null
layout_spectrum: 0.9369646201375872
typography_spectrum: 0.15763875260017812
title: Where you begin your understanding
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ba202a'
    - '#223e7d'
    - '#d263a7'
    - '#ffffff'
    - '#f2c1b1'
  brandStrength: 0.7904792514164001
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
